const ACTIVE_BUTTON_COLOR = '#000';
const INACTIVE_BUTTON_COLOR = '#aaa';
const BORDER_COLOR = '#e0e0e0';
const TEXT_COLOR = '#333';
const LIGHT_TEXT_COLOR = '#d0d0d0';

export {
  ACTIVE_BUTTON_COLOR,
  INACTIVE_BUTTON_COLOR,
  BORDER_COLOR,
  TEXT_COLOR,
  LIGHT_TEXT_COLOR,
};
